name: Deploy Sistema Controle Operacional API

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Verificar ambiente da VM
        run: |
          whoami
          docker --version
          docker compose version
          free -h
          docker system df


      - name: Atualizar projeto na VM
        run: |
          cd /srv/apps

          if [ ! -d "sistema-controle-operacional-api" ]; then
            git clone https://github.com/ALVAROVELAME/sistema-controle-operacional-api.git
          fi

          cd sistema-controle-operacional-api

          git fetch origin main
          git reset --hard origin/main


      - name: Parar container antigo
        run: |
          cd /srv/apps/sistema-controle-operacional-api

          docker compose down || true


      - name: Construir imagem Docker
        run: |
          cd /srv/apps/sistema-controle-operacional-api

          docker compose build


      - name: Iniciar API
        run: |
          cd /srv/apps/sistema-controle-operacional-api

          docker compose up -d


      - name: Verificar container
        run: |
          docker ps

          sleep 10

          docker logs --tail 50 sistema_controle_operacional_api


      - name: Limpar imagens antigas
        run: |
          docker image prune -f